[package]
name = "static_enum_dispatch"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
proc-macro = true


[dependencies]
proc-macro2 = { version = "1.0", features = ["nightly"] }
syn = {version="1.0", features=["full","fold", "extra-traits"]}
quote = "1.0"
